services:
  gauzy-app:
    image: gauzy-app
    build:
      context: .
      dockerfile: Dockerfile.prod
    restart: always
    networks:
      - overlay
    logging:
      options:
        max-size: 5m
    ports:
      - 3000:3000
      - 4200:4200
    # Note: Port exposure is disabled for microservices
    # Only enable ports if this service acts as a gateway
    environment:
      - NODE_ENV=production
    env_file:
      - .env

networks:
  overlay:
    name: overlay
    external: true
